config/routes.rb
Rails.application.routes.draw do
  resources :events
  root 'welcome#index'
  
  
 resources :customers  #esse comando gera varias rotas importantes

  get 'inicio' => 'welcome#index'
  get '/new' => 'customers#new'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/customer.rb
class Customer < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: %i[ show edit update destroy ]

  # GET /customers or /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1 or /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers or /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to customer_url(@customer), notice: "Customer was successfully created." }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1 or /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to customer_url(@customer), notice: "Customer was successfully updated." }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1 or /customers/1.json
  def destroy
    @customer.destroy

    respond_to do |format|
      format.html { redirect_to customers_url, notice: "Customer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def customer_params
      params.require(:customer).permit(:name, :email, :birthday, :obs)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def index 
        @teste = 'Curso de Rails'
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/customers/_customer.html.erb
<html>

<div id="<%= dom_id customer %>" style="padding-left:30rem; color:white; font-size:25px; text-shadow: 0.1em 0.1em 0.2em black; padding-top: 210px;">
 
<h1> Usuário Cadastrado com sucesso! </h1>

</div>

</html>

<style>
  html{
    background: url(<%= asset_path 'formulario.png' %>);
    background-position: center center;
    background-size: cover;
    background-position-y: 0px;
    background-repeat: no-repeat;
    
}

</style>

app/views/customers/_form.html.erb
<html >
<%= form_with(model: customer) do |form| %>
  <% if customer.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
        <% customer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div style='padding-left:40rem; color:white; font-size:25px; text-shadow: 0.1em 0.1em 0.2em black'>
  <div style='padding:10px;' >
    <%= form.label :nome%>
    <%= form.text_field :nome %>
  </div>

  <div style='padding:10px;'>
    <%= form.label :email%>
    <%= form.text_field :email %>
  </div>

  <div style='padding:10px;'>
    <%= form.label :Data_de_nascimento%>
    <%= form.date_field :Data_de_nascimento%>
  </div>

  <div style='padding:10px;'>
    <%= form.label :observação%>
    <%= form.text_area :observação%>
  </div>


  <div style='padding:10px;'>
    <%=form.submit %>
  </div>
  </div>

<% end %>
<html>

<style>
html {
    background: url(<%= asset_path 'formulario.png' %>);
    background-position: center center;
    background-size: cover;
    background-position-y: 0px;
    background-repeat: no-repeat;

}

</style>

app/views/customers/edit.html.erb
<h1>Editar dados de Usuário</h1>

<%= render "form", customer: @customer %>

<br>

<div>
  <button>
  <%= link_to "Mostrar Usuário", @customer %> |
  </button>
   <button>
  <%= link_to "Voltar ao início", customers_path %>
  </button>
</div>

app/views/customers/index.html.erb
<html style="background: #FFEFBA;  /* fallback for old browsers */
background: -webkit-linear-gradient(to right, #FFFFFF, #FFEFBA);  /* Chrome 10-25, Safari 5.1-6 */
background: linear-gradient(to right, #FFFFFF, #FFEFBA); /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
;">
<p style="color: green"><%= notice %></p>

<h1>Cadastro de Usuário</h1>

<div id="customers">
  <% @customers.each do |customer| %> 
    <%= render customer %>
    <p>
    <button>
      <%= link_to "Mostrar detalhes", customer %>
      </button>
    </p>
  <% end %>
</div>

<button>
<%= link_to "Fazer Cadastro", new_customer_path %>
<button>

</html>

app/views/customers/new.html.erb
<h1 style="padding-top: 180px;padding-left:37rem; font-family:sans-serif; color:white; text-shadow: 0.1em 0.1em 0.2em black, 0.1em 0.1em 0.2em black;  ">FAÇA SEU CADASTRO</h1>

<%= render "form", customer: @customer %>

<br>
<div style='padding-left:46rem;'>
<button class="botaovoltar">
  <%= link_to "Voltar", inicio_path, class:"voltar"%>
</button>
</div>

<style>
.voltar {
text-decoration:none;
}

.botaovoltar{
width:120px;
height:25px;
box-shadow: 2px 2px 2px rgba(0,0,0,0.2);
background: white; 
border-radius:8px;
}

.botaovoltar:hover{
    color: rgb(3, 238, 255);
    border: none;
}

</style>

app/views/customers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @customer %>

<div style="padding-left:40rem;">
<button class="editar">
  <%= link_to "Editar meus dados", edit_customer_path(@customer), class:"edita" %> |
  </button>
  <button class="voltar">
  <%= link_to "Voltar para o início", inicio_path, class:"volta" %>
  </button>
<br> <br>

</div>

<style>
   .edita {
     text-decoration:none;

   }
   
   .volta {
    text-decoration:none;
  }

</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Academia</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <style>
    @import url('https://fonts.googleapis.com/css2? family= Lato:ital@0;1 & display=swap');

/* Zerando o css,tirando as margens.Isso é padrao */
*{
    margin: 0%;
    padding: 0%;
    box-sizing: border-box;
}

/* Fundo tela */
html {
    width: 100%%;  /*Altura e largura inteira do html TOTAL*/
    height: 100%;
    font-size: 62.5%;
    color: white   
    
}
body{ /* Linear gradiente se refere ao fundo opaco mais degrade(gradiente)*/
    background: linear-gradient(rgb(17, 17, 17, 0.1), rgba(20, 20, 20, 1)), url(<%= asset_path 'academia.jpg' %>);
    background-position: center center;
    background-size: cover;
    background-position-y: 0px;
    background-repeat: no-repeat;
}

/* Menu - Header - Navbar */
header{
    width: 100%;
    height: 9vh;
    background: linear-gradient(rgb(17, 17, 20, 2.3), rgba(20, 20, 20, 0));
}

.menu-content{
    text-transform: uppercase; /*Deixa todas as letras maiusculas*/
    height: 100%; 
    display: flex; /*Logo de um lado e menu do outro*/
    justify-content: space-around; /*distanciamento deles no meio e entre as bordas*/
    align-items: center;
    font-size: 1.8rem;
}
.logo{
    font-size: 1.8rem;
    letter-spacing: 0.4rem; /*Espaço entre as letras*/
    cursor: pointer;
    font-family: sans-serif;
}
.menu-content .list-itens{
    display: flex;  /*para ficar um do lado do outro*/
    list-style: none;  /*pra tirar a bolinha padrao da lista*/
    gap: 10px; /*Distancia entre os itens do menu*/
}
.menu-content .list-itens a{
    text-decoration: none; /*Tira o sublinhado do link*/
    color: white;
    padding: 1.5rem; /*Aumenta a area de contato do cursor*/
    transition: 2ms ease-in;
    position: relative;
}
/* Before para gerar conteúdo e animação em uma determinada area */
.menu-content .list-itens a:before { 
  content: ' '; /*Todo before deve ter um content vazio*/
  position: absolute; 
  bottom: 0; /*A posição que começa*/
  left: 0;
  width: 0px; 
  border-radius: 40px;
  height: 2px; 
  background-color:rgb(3, 238, 255);
  transition: all 0.5s ease;
}
.menu-content .list-itens a:hover:before {
    width: 100px;
}
/* Centro - Conteúdo principal */
main {
    height: 91vh; /*O header ja estáutilizando 9vh da página,totalizando 100*/
    display: flex;
                        /*justify PARA CENTRALIZAR*/
    align-items: center;
}
.main-content {
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    padding-top: 80px;

}
@keyframes moveBanner {
    0%{
        transform: translateY(30rem) rotateY(-20deg);
    }
    100%{
        transform: translateY(0) rotateY(0);
    }
}
/* TEXTOS PRINCIPAIS */
.primary-text{
    width: 850px;
    font-size: 3.8rem;
    margin-bottom: 4rem; /*distanccia do texto pro botao*/
    text-align: center; /*Pro texto ficar centralizado*/
    font-family: monospace;
    animation: moveBanner 2.5s;
}
.second-text{
    margin-bottom: 5rem; /*Distancia entre os botoes*/
    font-size: 1.6rem;
    color: rgb(255, 255, 255);
    font-family: Verdana, Geneva, Tahoma, sans-serif;
    text-transform: uppercase;
    animation: moveBanner 3.1s;
}
    /* BOTOESSSS */
.btns {
    display: flex;
    justify-content: center;
    gap: 20px;
    animation: moveBanner 3.7s;
}
.btns button{
    width: 250px;
    height: 60px;
    cursor: pointer;
    border: 1px solid white;
    color: white;
    text-transform: uppercase;
    background-color: transparent;
    font-weight: bold; /*Letra mais cheia*/
    letter-spacing: 0.2rem;
    border-radius: 20px;
    position: relative;
    transition: 1s;
    text-decoration:none;
}
.btns button:hover{
    color: rgb(3, 238, 255);
    border: none;
}


.btns button:before {
    content: ' ';
    bottom: 0;
    left: 0;
    position: absolute;
    width: 0;
    height: 60px;
    background-color: rgba(160, 144, 144, 0.322);
    z-index: -1; /*O efeito não vai atrapalhar o texto no botão*/
    transition: 0.6s;
    border-radius: 20px; /*A mesma de cima*/
}

.btns button:hover:before {
    width: 100%;
}
.luis {
    text-decoration: none;
    color: white;
}

    </style>
    <title>Document</title>
</head>
<body>
     <header> <!-- Cabeçalho!!! -->
<div> 
      
</div>
        <div class="menu-content"> 
            <h1 class="logo">academiaEquilibrium</h1> 
            <nav class="header-menu"></nav> <!-- nav :Barra de navegaçao paera fazer menu -->
            <ul class="list-itens"> <!-- É uma lista não ordenada -->
                <li><a href="#">Home</a></li> <!-- <a> link dentro da lista <li> -->
                <li><a href="#">Pacotes</a></li> <!-- "#" sig. que não está ligando o link a nada -->
                <li><a href="#">Aulas</a></li>
                <li><a href="#">Unidades</a></li>
                <li><a href="#">Contatos</a></li>
                <li><a href="#"><i class="fab fa-facebook"></i></a></li>
                <li><a href="#"><i class="fab fa-instagram"></i></a></li>
            </ul>
        </div>
    </header>
    <main> <!-- Conteúdo principal/// -->
        <div class="main-content">
            <h1 class="primary-text">Apaixone-se por cuidar de si mesmo!</h1>
            <h2 class="second-text">Se inscreva agora e mude de vida</h2>
            <div class="btns">
                <button class="btn-exp">Agendar aula experimental</button>
                <button class="btn-personal"> <%= link_to 'Cadastre-se', '/new', class:"luis" %> </button>
            </div>
        </div>

    </main>

    

</body>
</html>